### ISSUE TITLE
有没有爬91的？

### ISSUE THREAD

**Issue by michaelzs1994** [cnbattle/douyin#1]

**Comment by cnbattle** [comment]
91是哪个网站?

**Comment by dulumao** [comment]
91手机助手

**Comment by yanzhao77** [comment]
你是真的皮

**Comment by QuincyC379** [comment]
有啊，我们一起研究下！还有个番茄社区，那个反爬是真的牛逼！

**Comment by 7ee3** [comment]
空手套网站/滑稽

**Comment by youxia2016** [comment]
91已可爬，爬取的只有默认画质视频，有VIP账号才能爬取高清画质
![91porn2](https://user-images.githubusercontent.com/16131728/90513790-c718fd80-e192-11ea-9f74-d574fe06afb7.png)
