### ISSUE TITLE
拦截的请求是不是对android7.0以上无效

### ISSUE THREAD

**Issue by losemy** [cnbattle/douyin#10]
安卓7.0之后，不在信任用户的证书了，问下这个是怎么弄的。
另外使用模拟器的教程有没有?

**Comment by cnbattle** [comment]
目前使用的是雷电模拟器正式版基于5.1的，真机上9.0 是有效的

目测是APP层的问题，新版本的抖音，APP层做的证书相关的处理，无法正常拦截抓取，你使用的抖音APP的版本是多少的？

**Comment by losemy** [comment]
最新版， 返回的数据变成了protobuf了，好难搞

**Comment by losemy** [comment]
发个可用的抖音apk?

**Comment by cnbattle** [comment]
豌豆荚有历史版本链接： https://www.wandoujia.com/apps/7461948/history_v710
