### ISSUE TITLE
Convert Int to String Error

### ISSUE THREAD

**Issue by hwangjr** [cnbattle/douyin#11]
https://github.com/cnbattle/douyin/blob/89e9eb057b01c8689ca04eefa389497a32cc501d/internal/core/core.go#L44
https://github.com/cnbattle/douyin/blob/89e9eb057b01c8689ca04eefa389497a32cc501d/internal/core/core.go#L45

Here should use `strconv.Itoa(int)` to convert int to string.

**Comment by cnbattle** [comment]
Yes, I have modified, thank you.
