### ISSUE TITLE
exit status 2

### ISSUE THREAD

**Issue by McQueenMI4** [cnbattle/douyin#9]
exit status 2 是什么问题

**Comment by cnbattle** [comment]
你是在哪一步报错的，能否描述的再具体些

**Comment by McQueenMI4** [comment]
anyproxy版运行报错 i/o timeout

**Comment by McQueenMI4** [comment]
解决了验证包网站是被墙了😂
但是为啥还没爬下来内容（求解

**Comment by cnbattle** [comment]
Anyproxy web页面是否看到了相关流量记录？

**Comment by McQueenMI4** [comment]
Anyproxy web页面有流量 也生成sqlite3数据库文件 就是没有文件下载
<img width="922" alt="截屏2020-05-10 下午12 22 46" src="https://user-images.githubusercontent.com/51505024/81490793-f62cf280-92b8-11ea-94c6-f554b3d9d0fc.png">

**Comment by cnbattle** [comment]
toml isDownload 是1吗 有改过吗

**Comment by McQueenMI4** [comment]
<img width="1466" alt="截屏2020-05-10 下午1 24 06" src="https://user-images.githubusercontent.com/51505024/81491470-896a2600-92c1-11ea-88c7-0d2edb56fe15.png">
没改过

**Comment by cnbattle** [comment]
smallLike 改成 0 试试  ，我不确定因为啥

**Comment by McQueenMI4** [comment]
<img width="1065" alt="截屏2020-05-10 下午1 57 25" src="https://user-images.githubusercontent.com/51505024/81491949-30e95780-92c6-11ea-98c1-e0b520cca9a3.png">
还是不行 ，是不是anyproxy配置的问题 这个具体是怎么配置的😃

**Comment by cnbattle** [comment]
0.0 没配置吗？

在电脑先到上面对应的目录里， 有个`rule_default.js`文件， 用git仓库里`anyproxy/rule_default.js` 替换，然后重新运行anyproxy

**Comment by McQueenMI4** [comment]
还是不行 😌

**Comment by cnbattle** [comment]
Anyproxy的证书安装了没？运行anyproxy有没有加 -i 开启https代理？

**Comment by McQueenMI4** [comment]
都不行🤷‍♂️

**Comment by cnbattle** [comment]
自己找找原因吧，我测试是可用的

**Comment by McQueenMI4** [comment]
好的谢谢
